name: pipeline dev

# trigger (gatilho)
on: 
  push: # o que vai ativar esse gatilho
    branches: ["DEV"] # e qual a branch que vai gerar o gatilho (["*"] todas as branches)

# define o que ele vai verificar
jobs:
  build:
    - uses: actions/checkout@v2 # entra na pasta do meu projeto
        
      - name: Configurar ambiente python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2
        
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Executar testes
        run: |
          coverage run -m python
          
      - name: Resultados
        run: coverage report
#Fim 
